events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $request - $status';
    access_log /var/log/nginx/access.log main;

    server {
        listen 8080;

        location /video/ {
            root /usr/share/nginx/html;
            add_header Cache-Control "public, max-age=60";
            add_header Access-Control-Allow-Origin "*";
        }
    }
}
