events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main '$remote_addr - $request - $status - Cache: $upstream_cache_status';
    access_log /var/log/nginx/access.log main;

    proxy_cache_path /var/cache/nginx
                     levels=1:2
                     keys_zone=cdn_cache:10m
                     max_size=1g
                     inactive=60m
                     use_temp_path=off;

    server {
        listen 80;

        # Reemplazar IP_PC1 con la IP real del servidor de origen antes de buildear
        set $origen http://IP_PC1:8080;

        location /video/ {
            proxy_pass $origen;
            proxy_cache cdn_cache;
            proxy_cache_valid 200 10m;
            proxy_cache_use_stale error timeout updating;

            add_header X-Cache-Status $upstream_cache_status;
            add_header Access-Control-Allow-Origin "*";
        }
    }
}
